##
## EPITECH PROJECT, 2018
## cpp
## File description:
## cpp
##


all:			
			cp 302separation.py ./302separation && chmod 755 ./302separation


clean:
			rm -rf 302separation

fclean: 		clean
				rm -rf __pycache__

re: 			fclean all


.PHONY: 		all clean fclean re
