##
## EPITECH PROJECT, 2018
## cpp
## File description:
## cpp
##


all:			
			cp pacman.py ./304pacman && chmod 755 ./304pacman


clean:
			rm -rf 304pacman

fclean: 		clean
				rm -rf __pycache__

re: 			fclean all


.PHONY: 		all clean fclean re
