##
## EPITECH PROJECT, 2018
## cpp
## File description:
## cpp
##


all:			
				cp construction.py ./305construction && chmod 755 ./305construction


clean:
				rm -rf 305construction

fclean: 		clean
				rm -rf __pycache__

re: 			fclean all


.PHONY: 		all clean fclean re
