##
## EPITECH PROJECT, 2018
## cpp
## File description:
## cpp
##


all:			
			cp 301dannon.py ./301dannon && chmod 755 ./301dannon


clean:
			rm -rf 301dannon

fclean: 		clean
				rm -rf __pycache__

re: 			fclean all


.PHONY: 		all clean fclean re
