##
## EPITECH PROJECT, 2018
## cpp
## File description:
## cpp
##


all:			
			cp 101pong.py ./101pong && chmod 755 ./101pong


clean:
			rm -rf 101pong

fclean: 		clean
				rm -rf __pycache__

re: 			fclean all


.PHONY: 		all clean fclean re
